os:
  - linux
  - osx
sudo: required
script:
  - make -f Bootstrap.mak $TRAVIS_OS_NAME
  - bin/release/premake5 test

deploy:
  provider: releases
  api_key: $GH
  draft: true
  overwrite: true
  file: bin/release/premake5
  skip_cleanup: true
  on:
    tags: true