language: c++
dist: trusty
sudo: false
sudo: required
  include:
  # Linux Debug
    - os: linux
      compiler: gcc
      env:
        - CONFIGURATION=debug
  # Linux Release
    - os: linux
      compiler: gcc
      env:
        - CONFIGURATION=release
  # macOS Debug x86
    - os: osx
      osx_image: xcode9
      env:
        - CONFIGURATION=debug
  # macOS Release x86
    - os: osx
      osx_image: xcode9
      env:
        - CONFIGURATION=release
script:
  - make -f Bootstrap.mak $TRAVIS_OS_NAME
  - make -C build/bootstrap -j config=debug
  - bin/release/premake5 test
  - bin/debug/premake5 test
  - cp bin/debug/premake5 bin/release/premake5d
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then (cd bin/release; tar -zcvf premake-linux.tar.gz premake5 premake5d; cd ../..) fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then (cd bin/release; tar -zcvf premake-macosx.tar.gz premake5 premake5d; cd ../..) fi
deploy:
  provider: releases
  api_key: $GH
  draft: true
  overwrite: true
  name: "$TRAVIS_TAG"
  tag_name: "$TRAVIS_TAG"
  file: "bin/release/*.tar.gz"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true