os:
  - linux
  - osx
sudo: required
script:
  - make -f Bootstrap.mak $TRAVIS_OS_NAME
  - bin/release/premake5 test

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -zcvf premake-linux.tar.gz -C bin/release; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tar -zcvf premake-macosx.tar.gz -C bin/release; fi
deploy:
  provider: releases
  api_key: $GH
  draft: true
  overwrite: true
  name: "$TRAVIS_TAG"
  tag_name: "$TRAVIS_TAG"
  file: "*.tar.gz"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true