os:
  - linux
  - osx
sudo: required
script:
 - bash scripts/install-travis.sh

 - make -f Bootstrap.mak $TRAVIS_OS_NAME
 - bin/release/premake5 test

deploy:
  description: 'ZPM Release'
  provider: GitHub
  auth_token: $env:GH
  artifact: bin/release/premake5
  draft: true
  prerelease: false
  on:
    appveyor_repo_tag: true 