os:
  - linux
  - osx
sudo: required
script:
  - make -f Bootstrap.mak $TRAVIS_OS_NAME
  - bin/release/premake5 test

deploy:
  - provider: releases
    api_key: $GH
    draft: true
    file: bin/release/premake5
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: $GH
    tag_name: development
    draft: true
    file: bin/release/premake5
    skip_cleanup: true
    on:
      branch: master