os:
  - linux
  - osx
sudo: required
script:
  - make -f Bootstrap.mak $TRAVIS_OS_NAME
  - bin/release/premake5 test

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then (cd bin/release; tar -zcvf premake-linux.tar.gz premake5; cd ../..) fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then (cd bin/release; tar -zcvf premake-macosx.tar.gz premake5; cd ../..) fi
deploy:
  provider: releases
  api_key: $GH
  draft: true
  overwrite: true
  name: "$TRAVIS_TAG"
  tag_name: "$TRAVIS_TAG"
  file: "bin/release/*.tar.gz"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true