os: Visual Studio 2015

platform:
  - Win32

before_build:
  - cmd: git clean -ffxd
  - cmd: git submodule sync
  - cmd: git submodule update --init

build_script:
  - cmd: call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat"
  - cmd: nmake -f Bootstrap.mak MSDEV=vs2015 windows

test_script:
  - cmd: bin\release\premake5 test


deploy:
  description: 'ZPM Release'
  provider: GitHub
  auth_token: "$env:GH"
  artifact: bin/release/premake5
  draft: true
  prerelease: false
  on:
    appveyor_repo_tag: true 