os: Visual Studio 2015

platform:
  - Win32

before_build:
  - cmd: git clean -ffxd
  - cmd: git submodule sync
  - cmd: git submodule update --init

build_script:
  - cmd: call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat"
  - cmd: nmake -f Bootstrap.mak MSDEV=vs2015 windows
  - cmd: (cd bin\release\ && 7z a premake-windows.zip premake5.exe && cd ../../)

test_script:
  - cmd: bin\release\premake5 test

artifacts:
  - path: bin\release\premake-windows.zip
    name: premake

deploy:
  description: 'ZPM Release'
  provider: GitHub
  auth_token: 
    secure: HHv48+XIpc9KD99ksjlsM2E7rQmpJ8xktezISBJi3Qu+w4uVMpoUNumDBQpk9fUq
  artifact: premake
  draft: true
  force_update: true
  prerelease: false
  on:
    appveyor_repo_tag: true
