os: Visual Studio 2015

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

before_build:
  - cmd: git clean -ffxd

build_script:
  - cmd: call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat"
  - cmd: nmake -f Bootstrap.mak MSDEV=vs2015 windows-ci
  - cmd: cd bin\release\
  - cmd: move ..\debug\premake5.exe .\premake5d.exe
  - cmd: 7z a premake-windows.zip premake5.exe 
  - cmd: 7z a premake-windows.zip premake5d.exe 
  - cmd: cd ../../

test_script:
  - cmd: bin\%CONFIGURATION%\premake5 test

artifacts:
  - path: bin\release\premake-windows.zip
    name: premake

deploy:
  description: 'ZPM Release'
  provider: GitHub
  auth_token: 
    secure: HHv48+XIpc9KD99ksjlsM2E7rQmpJ8xktezISBJi3Qu+w4uVMpoUNumDBQpk9fUq
  artifact: premake
  draft: true
  force_update: true
  prerelease: false
  on:
    appveyor_repo_tag: true
